In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
errs = pd.read_csv('../results/possible_errors_resnet152_cutmix_info.csv')
results = pd.read_csv('../human_eval_resnet152_cutmix.csv', header=None)
results.columns = ["index", "file", "valid"]
# results = results[results["index"] != "index"]
# results.columns = ["index", "file", "valid"]
# results = results.drop(231).reset_index(drop=True)
results = results.drop_duplicates(subset = ["file"], keep='last').reset_index(drop=True)
results

      index                                               file    valid
0         0  /Users/lisadunlap/data/imagenet-a/n01498041/0....       OK
1         1  /Users/lisadunlap/data/imagenet-a/n01498041/0....       OK
2         2  /Users/lisadunlap/data/imagenet-a/n01498041/0....       OK
3         3  /Users/lisadunlap/data/imagenet-a/n01498041/0....       OK
4         4  /Users/lisadunlap/data/imagenet-a/n01498041/0....       OK
...     ...                                                ...      ...
1524   1524  /Users/lisadunlap/data/imagenet-a/n12144580/0....       OK
1525   1525  /Users/lisadunlap/data/imagenet-a/n12267677/0....  INVALID
1526   1526  /Users/lisadunlap/data/imagenet-a/n12267677/0....       OK
1527   1527  /Users/lisadunlap/data/imagenet-a/n12267677/0....       OK
1528   1528  /Users/lisadunlap/data/imagenet-a/n12267677/0....       OK

[1529 rows x 3 columns]

In [34]:
results[results["valid"] != "OK"]

      index                                               file     valid
42       42  /Users/lisadunlap/data/imagenet-a/n01534433/0....  NOT SURE
81       81  /Users/lisadunlap/data/imagenet-a/n01580077/0....   INVALID
82       82  /Users/lisadunlap/data/imagenet-a/n01580077/0....   INVALID
92       92  /Users/lisadunlap/data/imagenet-a/n01614925/0....   INVALID
99       99  /Users/lisadunlap/data/imagenet-a/n01616318/0....   INVALID
...     ...                                                ...       ...
1514   1514  /Users/lisadunlap/data/imagenet-a/n11879895/0....   INVALID
1515   1515  /Users/lisadunlap/data/imagenet-a/n11879895/0....   INVALID
1521   1521  /Users/lisadunlap/data/imagenet-a/n12144580/0....   INVALID
1522   1522  /Users/lisadunlap/data/imagenet-a/n12144580/0....  NOT SURE
1525   1525  /Users/lisadunlap/data/imagenet-a/n12267677/0....   INVALID

[297 rows x 3 columns]

In [35]:
errs = pd.read_csv('../results/possible_errors_info.csv')
resnet50_results = pd.read_csv('../final_results.csv', header=None)
resnet50_results.columns = ["index", "file", "valid"]
# results = results[results["index"] != "index"]
resnet50_results = resnet50_results.drop(231).reset_index(drop=True)

replace = {}
for i, row in errs.iterrows():
    if resnet50_results.iloc[i]["index"] == "index":
        replace[i] = [i, row["image file"], "OK"]
        
for k in replace:
    resnet50_results.loc[k] = replace[k]

In [36]:
resnet50_results

    index                                               file    valid
0       0  /home/lisa/data/imagenet-a/n02106550/0.000190_...       OK
1       1  /Users/lisadunlap/data/imagenet-a/n02106550/0....  INVALID
2       2  /Users/lisadunlap/data/imagenet-a/n02106550/0....  INVALID
3       3  /Users/lisadunlap/data/imagenet-a/n02106550/0....  INVALID
4       4  /home/lisa/data/imagenet-a/n02106550/0.013400_...       OK
..    ...                                                ...      ...
403   403  /Users/lisadunlap/data/imagenet-a/n11879895/0....  INVALID
404   404  /Users/lisadunlap/data/imagenet-a/n11879895/0....  INVALID
405   405  /Users/lisadunlap/data/imagenet-a/n12144580/0....  INVALID
406   406  /home/lisa/data/imagenet-a/n12144580/0.002806_...       OK
407   407  /home/lisa/data/imagenet-a/n12144580/0.006141_...       OK

[408 rows x 3 columns]

In [37]:
resnet50_results[resnet50_results["valid"] == "INVALID"]

    index                                               file    valid
1       1  /Users/lisadunlap/data/imagenet-a/n02106550/0....  INVALID
2       2  /Users/lisadunlap/data/imagenet-a/n02106550/0....  INVALID
3       3  /Users/lisadunlap/data/imagenet-a/n02106550/0....  INVALID
11     11  /Users/lisadunlap/data/imagenet-a/n02669723/0....  INVALID
12     12  /Users/lisadunlap/data/imagenet-a/n02672831/0....  INVALID
..    ...                                                ...      ...
401   401  /Users/lisadunlap/data/imagenet-a/n11879895/0....  INVALID
402   402  /Users/lisadunlap/data/imagenet-a/n11879895/0....  INVALID
403   403  /Users/lisadunlap/data/imagenet-a/n11879895/0....  INVALID
404   404  /Users/lisadunlap/data/imagenet-a/n11879895/0....  INVALID
405   405  /Users/lisadunlap/data/imagenet-a/n12144580/0....  INVALID

[243 rows x 3 columns]

In [40]:
all_results = pd.concat([resnet50_results, results])
all_results = all_results.drop_duplicates(subset=['file'], keep='last')

In [41]:
all_results[all_results['valid'] == "INVALID"]

     index                                               file    valid
3        3  /Users/lisadunlap/data/imagenet-a/n02106550/0....  INVALID
29      29  /Users/lisadunlap/data/imagenet-a/n02787622/0....  INVALID
51      51  /Users/lisadunlap/data/imagenet-a/n02814860/0....  INVALID
58      58  /Users/lisadunlap/data/imagenet-a/n02879718/0....  INVALID
60      60  /Users/lisadunlap/data/imagenet-a/n02879718/0....  INVALID
...    ...                                                ...      ...
1513  1513  /Users/lisadunlap/data/imagenet-a/n11879895/0....  INVALID
1514  1514  /Users/lisadunlap/data/imagenet-a/n11879895/0....  INVALID
1515  1515  /Users/lisadunlap/data/imagenet-a/n11879895/0....  INVALID
1521  1521  /Users/lisadunlap/data/imagenet-a/n12144580/0....  INVALID
1525  1525  /Users/lisadunlap/data/imagenet-a/n12267677/0....  INVALID

[226 rows x 3 columns]

In [42]:
all_results[all_results['valid'] == "NOT SURE"]

     index                                               file     valid
42      42  /Users/lisadunlap/data/imagenet-a/n01534433/0....  NOT SURE
128    128  /Users/lisadunlap/data/imagenet-a/n01641577/0....  NOT SURE
159    159  /Users/lisadunlap/data/imagenet-a/n01677366/0....  NOT SURE
160    160  /Users/lisadunlap/data/imagenet-a/n01677366/0....  NOT SURE
186    186  /Users/lisadunlap/data/imagenet-a/n01694178/0....  NOT SURE
...    ...                                                ...       ...
1491  1491  /Users/lisadunlap/data/imagenet-a/n09246464/0....  NOT SURE
1493  1493  /Users/lisadunlap/data/imagenet-a/n09472597/0....  NOT SURE
1499  1499  /Users/lisadunlap/data/imagenet-a/n09472597/0....  NOT SURE
1512  1512  /Users/lisadunlap/data/imagenet-a/n11879895/0....  NOT SURE
1522  1522  /Users/lisadunlap/data/imagenet-a/n12144580/0....  NOT SURE

[111 rows x 3 columns]

In [44]:
crop_errors = pd.read_csv("../results/possible_errors_info.csv")
crop_errors

,error,crop corr,target,pred,ratio,image file,target imagenet class,target class name,pred imagenet class,pred class name
0,2783,4,39,90,0.501158,/home/lisa/data/imagenet-a/n02106550/0.000190_...,234,Rottweiler,456,bow
1,2784,4,39,68,4.581006,/home/lisa/data/imagenet-a/n02106550/0.000342_...,234,Rottweiler,347,bison
2,2794,4,39,85,0.506504,/home/lisa/data/imagenet-a/n02106550/0.004504_...,234,Rottweiler,428,wheelbarrow
3,2796,4,39,152,0.157435,/home/lisa/data/imagenet-a/n02106550/0.004684_...,234,Rottweiler,792,shovel
4,2808,1,39,105,0.329777,/home/lisa/data/imagenet-a/n02106550/0.013400_...,234,Rottweiler,539,doormat
...,...,...,...,...,...,...,...,...,...,...
403,7449,6,196,6,1.364541,/home/lisa/data/imagenet-a/n11879895/0.004490_...,984,rapeseed,23,vulture
404,7450,4,196,178,1.249446,/home/lisa/data/imagenet-a/n11879895/0.006992_...,984,rapeseed,913,shipwreck
405,7470,3,198,179,3.104385,/home/lisa/data/imagenet-a/n12144580/0.002667_...,987,corn,924,guacamole
406,7472,2,198,188,4.353742,/home/lisa/data/imagenet-a/n12144580/0.002806_...,987,corn,954,banana
407,7476,2,198,54,1.048633,/home/lisa/data/imagenet-a/n12144580/0.006141_...,987,corn,311,grasshopper

In [48]:
resnet50_results2 = resnet50_results
resnet50_results2.columns = ["index", "image file", "valid"]
resnet50_results2["image file"] = [r.replace("Users/lisadunlap", "home/lisa") for r in resnet50_results2["image file"]]
new_dat = pd.merge(crop_errors, resnet50_results, on="image file")

In [50]:
new_dat.to_csv("../results/possible_errors_results.csv", index=False)